### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by Galhali** [klukule/merlin#10]
When i got 2 nodes near each other, when i finished one and want go to other one patht is just one short line but it make player stuck. I stayed mounted have 2 meters to next node but player just standing in one place.

**Comment by Deathwing** [comment]
Maybe fixed with:
https://github.com/klukule/merlin/pull/11

**Comment by Galhali** [comment]
I will check and let you know.

**Comment by klukule** [comment]
Closing as no response about fix was stated, presuming was successfully fixed.
