### ISSUE TITLE
Bug: Magic Arrow spell doesn't work

### ISSUE THREAD

**Issue by klukule** [klukule/merlin#18]
User on discord said that this spell fails to cast "Invalid target"

More details about the spell:
https://albiononlinedatabase.com/spell/SKILLSHOT_STUN

**Comment by Deathwing** [comment]
I will make a bill to you, for the costs of the T4 warbow :-D

**Comment by Deathwing** [comment]
Should be fixed with current testing version (API-develop).
Please report back.

**Comment by klukule** [comment]
Fixed in 93699ac
