### ISSUE TITLE
freeze banking @ Martlock 

### ISSUE THREAD

**Issue by minsmids** [klukule/merlin#19]
It perfectly finds a route and stores items to bank, but freezes on the way out.

It happens, then you go out of the bank place. I guess the freeze happens because of finding a path to the gathering location. Freezes both for the South/West/East ways from Martlock.

**Comment by Deathwing** [comment]
Can you tell me which Gathering Cluster you provided? Cause like you said, it seems to break on going back to your gathering cluster.

**Comment by minsmids** [comment]
@Deathwing Mase Knoll

**Comment by Monkey7539** [comment]
I've made some changes to both banking and repairing recently that should resolve this issue. If someone can test I would appreciate it.
