### ISSUE TITLE
Create a "How to use" guide

### ISSUE THREAD

**Issue by fabriciorissetto** [klukule/merlin#23]
I suggest (and want to help you with that very soon) to create a guide for "users" with the features that the bot supports.

Also would be nice to create a guide (not sure how much difficult it would be) for "developers" who want to contribute. Things like "where to start", "the main things they need to know", "design conventions".

**Comment by klukule** [comment]
Well I'm currently working on "How to download & Install (+ launch) merlin" for casual users, but sadly I don't have much time :) so it will take a little bit... and then I could maybe make something... and i know that for example "Design conventions" should have been done way in the past... but because it's only me + Deathwing (mostly) working on the code itself we had only some informal rules (aka no rules :D )

**Comment by favasconcelos** [comment]
Found this in one of the forks:

```
How to use MERLIN (Albion Bot):
#1 go to https://github.com/klukule/merlin
#2 download zip
#3 extract the said zip file to C:\
#4 open C:\merlin-master\Albion\Merlin.sln with visual studio 2017
#5 click browse
#6 then click the other browse
#7 navigate to C:\Program Files (x86)\AlbionOnline\game\Albion-Online_Data\Managed\ (or wherever you installed your game)
... and click OK
#8 Build the solution
#8.1 Successful compile? Proceed to #9.  Compile with NuGet error?  Proceed to 8.1
#8.2 Run your Visual Studio 2017 installer once again https://www.visualstudio.com/downloads/
#8.3 Customize your installed packages -> click dropdown -> choose modify
#8.3 Choose individual components
#8.4 Choose NuGet package manager
#8.5 click modify on lower right -> then wait for installation to finish.
#8.6 Try rebuilding once again, it should succeed now.
#9 run C:\merlin-master\albion-load.bat
#10 you should then see, Gathering UI in top center of your game client
#11 Customize the settings
#12 Click Start Gathering
Congratulations!
```
Maybe this help's?

**Comment by klukule** [comment]
I totally forgot about that one :) It should be working... so it's possible to use this as a guide

**Comment by favasconcelos** [comment]
Can you kinda "describe" a bit more about 5,6 and 7, it's kinda OFF to me what should be done xD

**Comment by klukule** [comment]
or:
Create folder `Dependencies` in `merlin-master\Albion\`
Copy all DLLs from `AlbionOnline\game\Albion-Online_Data\Managed` to `Dependencies` folder
and you're done

**Comment by klukule** [comment]
Created WIKI page for [Download & Install guide](https://github.com/klukule/merlin/wiki/How-to-Download-&-Install)
