### ISSUE TITLE
Bot banking and repairing effeciency

### ISSUE THREAD

**Issue by lemon07r** [klukule/merlin#44]
Bot can be made more efficient if it did both banking and repairing every time it returned to city to do either task instead of doing just the single job it needed to, e.a. right now bot will only bank if it doesn't need to repair, then come back later to repair instead of doing it all in the same trip.

**Comment by rmicko** [comment]
And when is bank open effective would be also refill pies of higher tier in bank?

**Comment by rmicko** [comment]
Now i checked few times how banking is working... Are not bot moving items so fast? Can be added some delay betwen stacks movement to be more human like?

**Comment by Monkey7539** [comment]
I added this and tested slightly so it should be okay .
